name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: eduardoc7
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC-3
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: eduardoc7
          plugin_languages_analysis_timeout: 20
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage
          plugin_languages_other: false
          plugin_languages_ignored: ruby
          plugin_languages_limit: 10,
          plugin_languages_recent_categories: programming, data, markup, prose
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_topics: yes
          plugin_topics_limit: 30
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_repositories: yes
          plugin_repositories_pinned: 2
          plugin_repositories_starred: 3
